version: 2.1

orbs:
  eq: equisoft/build-tools@0.0.15

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - eq/phpunit:
          checkout: true
      - eq/psalm :
          extra-build-args : --no-diff
          checkout : true
